services:
  postgres:
    image: postgres:14
    container_name: postgres_project
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:
    build:
      context: ./extract_load
      dockerfile: dockerfile
    container_name: etl_container
    env_file: .env
    environment:
    - ENV=docker 
    volumes:
      - ./extract_load/data:/app/data
    depends_on:
      - postgres
  dbt:
    build:
      context: ./transform/perfume_project
      dockerfile: dockerfile
    container_name: dbt_container
    volumes:
      - ./transform/perfume_project:/app
    working_dir: /app
    depends_on:
      - postgres

volumes:
  postgres_data:
