services:
  postgres:
    image: postgres:14
    container_name: postgres_project
    environment:
      POSTGRES_USER: quang
      POSTGRES_PASSWORD: q
      POSTGRES_DB: product
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  etl:
    build:
      context: ./extract_load
      dockerfile: dockerfile
    container_name: etl_container
    env_file: .env
    volumes:
      - ./extract_load/data:/app/data
    depends_on:
      - postgres

volumes:
  postgres_data:
