services:
  postgres:
    image: postgres:14
    container_name: postgres_project
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT_DOCKER}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:
    build:
      context: ./extract_load
      dockerfile: dockerfile
    container_name: etl_container
    env_file: .env
    environment:
    - ENV=docker 
    volumes:
      - ./extract_load/data:/app/data
    depends_on:
      - postgres
  dbt:
    build:
      context: ./transform/perfume_project
      dockerfile: dockerfile
    container_name: dbt_container
    volumes:
      - ./transform/perfume_project:/app
    working_dir: /app
    depends_on:
      - postgres

  airflow-init:
    image: apache/airflow:2.1.1-python3.8
    container_name: airflow_init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    command: >
      /bin/bash -c "
        airflow db init &&
        airflow users create -u admin -p airflow -f admin -l user -r Admin -e admin@example.com
      "
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs_airflow:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  airflow-webserver:
    image: apache/airflow:2.1.1-python3.8
    container_name: airflow_web
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    command: webserver
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs_airflow:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
      - ./extract_load:/opt/airflow/dags/extract_load
      - /var/run/docker.sock:/var/run/docker.sock         
      - /tmp:/tmp 

  airflow-scheduler:
    image: apache/airflow:2.1.1-python3.8
    container_name: airflow_scheduler
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs_airflow:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
      - ./extract_load:/opt/airflow/dags/extract_load
      - /var/run/docker.sock:/var/run/docker.sock         
      - /tmp:/tmp 
volumes:
  postgres_data:
